construction/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)        

home/urls.py
from django.urls import path
from . views import index,ServiceList,get_service,contact_form
urlpatterns = [
    path('', index,name='index'),
    path('service/<pk>',get_service),
    path('services/',ServiceList.as_view(),name='services'),
    path('contact/',contact_form,name='contact'),


]

home/models.py
from django.db import models

# Create your models here.


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category


class Unit(BaseModel):
    unit = models.CharField(max_length=50)

    def __str__(self):
        return self.unit


class Advantage(BaseModel):
    advantage = models.CharField(max_length=200)

    def __str__(self):
        return self.advantage


class Service(BaseModel):
    title = models.CharField(max_length=500)
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='services')
    price = models.PositiveIntegerField()
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    meta_title = models.CharField(max_length=200)
    meta_description = models.CharField(max_length=500)
    advantages = models.ManyToManyField(Advantage)

    def __str__(self):
        return self.title


class Image(BaseModel):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='images/')
    alt_text = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.alt_text} {self.is_head_image}'


class ServiceRequest(BaseModel):
    service = models.ForeignKey(Service, on_delete=models.CASCADE,
                                related_name='service_request', blank=True, null=True)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=13)
    email = models.EmailField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} - {self.service} - {self.phone_number}'


class Member(BaseModel):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')
    position = models.CharField(max_length=100)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Social(BaseModel):
    choices = (
        ('facebook', 'ri-facebook-fill'),
        ('twitter', 'ri-twitter-fill'),
        ('instagram', 'ri-instagram-fill'),
        ('linkedin', 'ri-linkedin-box-fill'),
    )
    name = models.CharField(max_length=100)
    icon_class = models.CharField(choices=choices, max_length=100)
    link = models.CharField(max_length=500)
    member = models.ForeignKey(
        Member, on_delete=models.CASCADE, related_name='socials')

    def __str__(self):
        return self.name


class FAQ(BaseModel):
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return self.question


class CompanyDetails(models.Model):
    name = models.CharField(max_length=50)
    phone_number = models.PositiveIntegerField()
    address = models.CharField(max_length=300)
    email = models.EmailField()
    twitter_link = models.CharField(max_length=200,default="#")
    facebook_link = models.CharField(max_length=200,default="#")
    instagram_link = models.CharField(max_length=200,default="#")
    linkedin_link = models.CharField(max_length=200,default="#")
    map_link = models.CharField(max_length=500,default="#")
    
    def __str__(self):
        return "Company Details"


class HeadDetails(models.Model):
    text = models.CharField(max_length=100)
    video_link = models.CharField(max_length=500,default="#")
    
    def __str_(self):
        return "Heading Details"


class AboutUsText(models.Model):
    text = models.TextField()
    def __str_(self):
        return "Aboutus section text"

class ServicesText(models.Model):
    text = models.TextField()
    def __str_(self):
        return "Services section text"


class ContactNowText(models.Model):
    text = models.TextField()
    def __str_(self):
        return "Contactnow  section text"


class ContactText(models.Model):
    text = models.TextField()
    
    def __str_(self):
        return "contact section text"

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . models import (
    ServiceRequest
)

class ServiceRequsetForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['service','name','phone_number','email','description']
        
    
class UserForm(UserCreationForm):
    class Meat:
        model = UserCreationForm
        fields = '__all__'

home/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect

from django.views.generic import ListView
from django.contrib import messages
from . forms import ServiceRequsetForm

from django.http import HttpResponse


from . models import (
    Service,
    Image,
    Category,
    FAQ,
    Member,
    HeadDetails,
    CompanyDetails,
    AboutUsText,
    ServicesText,
    ContactNowText,
    ContactText

)
# Create your views here.

# home page


def index(request):

    services = Service.objects.all()[:3]
    faqs = FAQ.objects.all()
    members = Member.objects.all()

    context = {
     
        'services': services,
        'faqs': faqs,
        'members': members,
        'head_details': HeadDetails.objects.last(),
        "company_details": CompanyDetails.objects.last(),
        'about_us_text': AboutUsText.objects.last(),
        "services_text": ServicesText.objects.last(),
        "contact_now_text": ContactNowText.objects.last(),
        'contact_text': ContactText.objects.last()
    }

    return render(request, 'home/index.html', context)


def get_service(request, pk):
    service = Service.objects.filter(id=pk)
    if not service.exists():
        messages.error(request, '404 introuvables !')
        return redirect('index')
    form = ServiceRequsetForm
    if request.method == 'POST':
        form = ServiceRequsetForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Demande soumise avec succès')
    return render(request, 'home/service_detail.html', {'service': service[0], 'form': form, "company_details": CompanyDetails.objects.last()})


class ServiceList(ListView):
    model = Category
    template_name = 'home/services.html'
    context_object_name = 'categories'

    def get_queryset(self):
        queryset = super().get_queryset()
        cat = self.request.GET.get('category', None)
        if cat is not None:
            queryset = queryset.filter(category__icontains=cat)
        return queryset

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        data = super().get_context_data(**kwargs)
        data['company_details'] = CompanyDetails.objects.last()
        return data


def contact_form(request):
    if request.method == "POST":
        form = ServiceRequsetForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('OK')
        return HttpResponse('None')

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}
        
    {% endblock title %}</title>
  <meta content="{% block meta_description %}
    
  {% endblock meta_description %}" name="description">


  <!-- Favicons -->
  <link href="" rel="icon">


  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %} " rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %} " rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %} " rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %} " rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel ="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %} " rel="stylesheet">
  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %} " rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'index' %}">{{company_details.name}}</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="{% static 'img/logo.png' %} " alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'index' %}">Domicile</a></li>
          <li><a class="nav-link scrollto" href="http://127.0.0.1:8000/#about">Environ</a></li>
          <li><a class="nav-link scrollto" href="http://127.0.0.1:8000/#services">Services</a></li>
          <li><a class="nav-link   scrollto" href="http://127.0.0.1:8000/#portfolio">Portefeuille</a></li>
          <li><a class="nav-link scrollto" href="http://127.0.0.1:8000/#team">Équipe</a></li>
          <li><a class="nav-link scrollto" href="http://127.0.0.1:8000/#contact">Contact</a></li>

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block body %}
  {% endblock body %}

  <!-- ======= Footer ======= -->
  <footer id="footer">


    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>{{company_details.name}}</h3>
            <p>
            {{company_details.address|title}}
            <br>
              <strong>Phone:</strong>{{company_details.phone_number}}<br>
              
              <strong>Email:</strong>{{company_details.email}}<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Liens utiles</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'index' %}">Domicile</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="http://127.0.0.1:8000/#about">Environ</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="http://127.0.0.1:8000/#services">Services</a></li>
              <li><i class="bx bx-chevron-right"></i><a href="http://127.0.0.1:8000/#portfolio">Portefeuille</a></li>
              <li><i class="bx bx-chevron-right"></i><a href="http://127.0.0.1:8000/#team">Équipe</a></li> 

            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Nos services</h4>
            <ul>

              <li><i class="bx bx-chevron-right"></i> <a href="#services">Imperméabilisation</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#services">Ignifugation</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Nos réseaux sociaux</h4>

            <div class="social-links mt-3">
              <a href="{{company_details.twitter_link}}" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="{{company_details.facebook_link}}" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="{{company_details.instagram_link}}" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="{{company_details.linkedin_link}}" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container footer-bottom clearfix">
      <div class="copyright">
        &copy; Copyright <strong><span>{{company_details.name}}</span></strong>. Tous droits réservés
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/ -->
        Conçu par <a href="#">Name</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>
  {% block js %}{% endblock js %}

</body>

</html>

templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
<!-- ======= Hero Section ======= -->
{% block body %}



<section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-7 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1"
                data-aos="fade-up" data-aos-delay="200">
                <h1>{{head_details.text}}</h1>

                <div class="d-flex justify-content-center justify-content-lg-start">
                    <a href="{% url 'services' %}" class="btn-get-started scrollto">Démarrer</a>
                    <a href="{{head_details.video_link}}" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Regarder la
                            vidéo</span></a>
                </div>
            </div>
            <div class="col-lg-5 order-1 order-lg-2 hero-img " data-aos="zoom-in" data-aos-delay="200">
                <img src="{% static 'img/home head.jpg' %}" class="img-fluid animated w-75" alt="">
            </div>
        </div>
    </div>

</section><!-- End Hero -->

<main id="main">


    <!-- ======= About Us Section ======= -->
    <section id="about" class="about">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>QUI SOMMES-NOUS</h2>
            </div>

            <div class="row content">
                
                 <p>
                    {{about_us_text.text}}
                 </p>
                </div>
            </div>

        </div>
    </section><!-- End About Us Section -->

    <!-- ======= Services Section ======= -->
    <section id="services" class="services section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>PRESTATIONS DE SERVICE</h2>
                <p>{{service_text.text}}</p>
            </div>

            <div class="row">
                <div class="col-xl-6 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                    <div class="icon-box">
                        <div class="icon"><i class='bx bxs-hot'></i></div>
                        <h4><a href="/services?category=Ignifugation">Ignifugation</a></h4>
                        <p>Les services d'ignifugation fournissent une couche de défense essentielle, garantissant que
                            votre propriété reste résiliente face aux risques d'incendie potentiels.</p>
                    </div>
                </div>

                <div class="col-xl-6 col-md-6 d-flex align-items-stretch mt-4 mt-md-0" data-aos="zoom-in"
                    data-aos-delay="200">
                    <div class="icon-box">
                        <div class="icon"><i class='bx bx-water'></i></div>
                        <h4><a href="/services?category=insonorisation">Étanchéité</a></h4>
                        <p>Les services d'imperméabilisation offrent une barrière fiable contre l'intrusion d'eau,
                            protégeant votre propriété contre les dommages causés par l'humidité et préservant son
                            intégrité structurelle.</p>
                    </div>
                </div>
            </div>
            <div class="text-center mt-4">

                <a href="{% url 'services' %}" class="btn-get-started scrollto mt-4 ">Explorer tous les services</a>
            </div>
        </div>
    </section><!-- End Services Section -->

    <!-- ======= Cta Section ======= -->
    <section id="cta" class="cta">
        <div class="container" data-aos="zoom-in">

            <div class="row">
                <div class="col-lg-9 text-center text-lg-start">
                    <h3>Appelez-nous</h3>
                    <p> {{contact_now_text.text}}</p>
                </div>
                <div class="col-lg-3 cta-btn-container text-center">
                    <a class="cta-btn align-middle" href="#contact">Appelez-nous</a>
                </div>
            </div>

        </div>
    </section><!-- End Cta Section -->

    <!-- ======= Portfolio Section ======= -->
    <section id="portfolio" class="portfolio">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>PORTEFEUILLE</h2>

            </div>



            <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
            {% for service  in services %}
                <div class="col-lg-4 col-md-6 portfolio-item ">
                    <div class="portfolio-img"><img src="{{service.images.first.image.url}}" class="img-fluid" alt="">
                    </div>
                    <div class="portfolio-info">
                        <h4>{{service.title}}</h4>
                        <p>{{service.meta_title|truncatechars:60}}</p>
                  
                        <a href="/service/{{service.id}}" class="details-link" title="Plus de détails"><i
                                class="bx bx-link"></i></a>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </section><!-- End Portfolio Section -->

    <!-- ======= Team Section ======= -->
    <section id="team" class="team section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>ÉQUIPE</h2>
               
            </div>

            <div class="row">

                <div class="col-lg-6" data-aos="zoom-in" data-aos-delay="100">
                    {% for member in members %}
                    <div class="member d-flex align-items-start">
                        <div class="pic"><img src="{{member.image.url}}" class="img-fluid" alt=""></div>
                        <div class="member-info">
                            <h4>{{member.name|title}}</h4>
                            <span>{{member.position}}</span>
                            <p>{{member.description}}</p>
                            <div class="social">
                                {% for social in member.socials.all %}
                                <a href="{{social.link}}"><i class="{{social.get_icon_class_display}}"></i></a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
    </section><!-- End Team Section -->



    <!-- ======= Frequently Asked Questions Section ======= -->
    <section id="faq" class="faq section-bg">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Questions fréquemment posées</h2>
              
            </div>

            <div class="faq-list">
                <ul>
                    {% for faq in faqs %}
                    <li data-aos="fade-up" data-aos-delay="100">
                        <i class="bx bx-help-circle icon-help"></i> <a data-bs-toggle="collapse" class="collapse"
                            data-bs-target="#faq-list-1">{{faq.question}}<i
                                class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
                        <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                            <p>
                               {{faq.answer}}
                            </p>
                        </div>
                    </li>
                    {% endfor %}

                </ul>
            </div>

        </div>
    </section><!-- End Frequently Asked Questions Section -->

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
        <div class="container" data-aos="fade-up">

            <div class="section-title">
                <h2>Contact</h2>
                <p>{{contact_text.text}}</p>
            </div>

            <div class="row">

                <div class="col-lg-5 d-flex align-items-stretch">
                    <div class="info">
                        <div class="address">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Emplacement:</h4>
                            <p>{{company_details.address}}</p>
                        </div>

                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <h4>E-mail:</h4>
                            <p>{{company_details.email}}</p>
                        </div>

                        <div class="phone">
                            <i class="bi bi-phone"></i>
                            <h4>Appel:</h4>
                            <p>{{company_details.phone_number}}</p>
                        </div>

                        <iframe
                            src="{{company_details.map_link}}"
                            frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
                    </div>

                </div>

                <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch">
                    <form action="{% url 'contact' %}" method="post" role="form" class="php-email-form">
                        {% csrf_token %}
                        <input type="hidden" name="form_type" value="contact_form">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="name">Votre nom</label>
                                <input type="text" name="name" class="form-control" id="name" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="email">Votre e-mail</label>
                                <input type="email" class="form-control" name="email" id="email" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="phone">Phone Number</label>
                            <input type="text" class="form-control" name="phone_number" id="phone" required>
                        </div>
                        <div class="form-group">
                            <label for="description">Message</label>
                            <textarea class="form-control" name="description" rows="10" required></textarea>
                        </div>
                        <div class="my-3">
                            <div class="loading">Chargement</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Votre message a été envoyé. Merci!</div>
                        </div>
                        <div class="text-center"><button type="submit">Envoyer le message</button></div>
                    </form>
                </div>

            </div>

        </div>
    </section><!-- End Contact Section -->

</main><!-- End #main -->
{% endblock body %}

templates/home/service_detail.html
{% extends 'home/base.html' %}
{% load my_tags %}

{% block meta_description %}
{{service.meta_description}}
{% endblock meta_description %}
{% block title %}
{{service.meta_title}}
{% endblock title %}
{% block body %}

<div class="temp-div d-flex align-items-center justify-content-center">

    <h1 class='white'>{{service.title|title}}</h1>

</div>

<div class="section-bg services">

<div class=" icon-box   mb-4 ">
    <div class="text-center">
  
        <div id="carouselExample" class="carousel slide">
            <div class="carousel-inner">
            {% for image in service.images.all  %}
              <div class="carousel-item 
              {% if forloop.counter == 1 %}
              active
              {% endif %}
              
              ">
                <img src="{{image.image.url}}" class="d-block " alt="{{image.alt_text}}">
              </div>
              {% endfor %}
    
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
           

        

    </div>
    <h6 class="mt-4 blue text-center">
        {{service.meta_title|title}}
    </h6>
        <h5 class="blue">

            <span>Prix : </span>
            <span class=" text-success">€ {{service.price}}/{{service.unit}}</span>
        </h5>

    <h5 class='mt-4 blue'>
        <span class="h5">Catégorie  : <span class="badge bg-secondary">{{service.category|title}}</span></span>
    </h5>
    <div class="mt-3">
        <h5 class="blue">Avantages:</h5>
        <ul class="mt-2">
            {% for advantage in service.advantages.all %}
            <li>{{advantage}}</li>   
            {% endfor %}
        </ul>
    </div>
    <div class="mt-4">
        <h5 class="blue">Description:</h5>
        <p class="mt-3 p">
            {{service.description}}
        </p>
    </div>

</div>
<section id="contact" class="contact">
    <div class="container"  data-aos="fade-up">
            <div class="h2 mt-4 mb-4 blue text-center fw-bold">
                CONTACT
            </div>
            <div class=" mt-5  d-flex align-items-stretch">
                <form action="{% url 'contact' %}" method="post" role="form" class="php-email-form">
                    {% csrf_token %}
                    <input type="hidden" value="{{service.id}}" name = "service">

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name">Votre nom</label>
                            <input type="text" name="name" class="form-control" id="name" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="email">Votre e-mail</label>
                            <input type="email" class="form-control" name="email" id="email" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone">Phone Number</label>
                        <input type="text" class="form-control" name="phone_number" id="phone" required>
                    </div>
                    <div class="form-group">
                        <label for="description">Message</label>
                        <textarea class="form-control" name="description" rows="10" required></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Chargement</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Votre message a été envoyé. Merci!</div>
                    </div>
                    <div class="text-center"><button type="submit">Envoyer le message</button></div>
                </form>
            </div>

    </div>
</section><!-- End Contact Section -->
</div>

{% endblock body %}

templates/home/services.html
{% extends 'home/base.html' %}
{% load static %}
{% block css %}
<style>


</style>
{% endblock css %}
{% block body %}

<div class="temp-div d-flex align-items-center justify-content-center">

    <h1 class='white'>Tous les services</h1>

</div>
<div id="services" class="services section-bg">
    <div class="container mb-4">

        {% for category in categories %}
        <h2 class="p-4 text-center fw-bold">{{category|title}}</h2>
        <div class="mt-4 mb-4">
            <div class="row ">
                {% for service in category.services.all %}
                <div class="col-xl-6 col-md-6 d-flex align-items-stretch justifyc" data-aos="zoom-in" data-aos-delay="100">
                    <div class="icon-box">
                        <div class="text-center">

                            <img src="{{service.images.first.image.url}}" class="img-thumbnail rounded-start mx" alt="{{service.images.first.image.alt_text}}">
                        </div>

                        <div class="mt-4">
                            <h4><a href="/service/{{service.id}}">{{service.title|title}}</a></h4>
                            <p>
                                {{service.meta_description|truncatechars:150}}
                            </p>
                            <a href="/service/{{service.id}}" class="btn-get-started  mt-4 ">Explorer</a>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock body %}